name: E-commerce Cabuloso
description: Você foi contratado para ajudar a criar um protótipo de sistema de e-commerce do nosso amigo Kleber Cabuloso.
publish_to: 'none'
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
